// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFksCA2fjxDEvnGwgQRc2TtXvHPIuDApw',
    appId: '1:297645474572:web:df4968b475a4e9c5dcff29',
    messagingSenderId: '297645474572',
    projectId: 'belajarcrud-30bb5',
    authDomain: 'belajarcrud-30bb5.firebaseapp.com',
    storageBucket: 'belajarcrud-30bb5.firebasestorage.app',
    measurementId: 'G-DWYRTFVBZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK5Uk2Yiv_dfhNsay_Yr8HQ3i-Hr8kSbw',
    appId: '1:297645474572:android:2732f5ffe6da8813dcff29',
    messagingSenderId: '297645474572',
    projectId: 'belajarcrud-30bb5',
    storageBucket: 'belajarcrud-30bb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCpYEWiiaXrQotKM_A3VCtljuU9VE4dEU',
    appId: '1:297645474572:ios:a7cf731fe6987f12dcff29',
    messagingSenderId: '297645474572',
    projectId: 'belajarcrud-30bb5',
    storageBucket: 'belajarcrud-30bb5.firebasestorage.app',
    iosClientId: '297645474572-of2bok2agsaknacljgc9k3d08ac3h610.apps.googleusercontent.com',
    iosBundleId: 'com.example.slicing1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCpYEWiiaXrQotKM_A3VCtljuU9VE4dEU',
    appId: '1:297645474572:ios:a7cf731fe6987f12dcff29',
    messagingSenderId: '297645474572',
    projectId: 'belajarcrud-30bb5',
    storageBucket: 'belajarcrud-30bb5.firebasestorage.app',
    iosClientId: '297645474572-of2bok2agsaknacljgc9k3d08ac3h610.apps.googleusercontent.com',
    iosBundleId: 'com.example.slicing1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFksCA2fjxDEvnGwgQRc2TtXvHPIuDApw',
    appId: '1:297645474572:web:fadb97086b9d494cdcff29',
    messagingSenderId: '297645474572',
    projectId: 'belajarcrud-30bb5',
    authDomain: 'belajarcrud-30bb5.firebaseapp.com',
    storageBucket: 'belajarcrud-30bb5.firebasestorage.app',
    measurementId: 'G-GTCRS0KKG4',
  );
}
